/**
 * Generates lib/monaco/react-types.generated.ts from the installed type packages.
 *
 * The Monaco TS worker runs in the browser and cannot read node_modules, so the
 * .d.ts sources are embedded as string constants and registered via addExtraLib.
 * Re-run after bumping @types/react, csstype, or @types/prop-types:
 *
 *   pnpm exec tsx scripts/generate-editor-types.ts
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// Virtual paths mirror node_modules so Monaco's NodeJs module resolution finds
// them for `import 'react'`, the `/// <reference path="global.d.ts" />` in
// @types/react, and the csstype / prop-types imports inside it.
const LIBS: Array<{ pkg: string; file: string; virtualPath: string }> = [
  {
    pkg: '@types/react',
    file: 'index.d.ts',
    virtualPath: 'file:///node_modules/@types/react/index.d.ts',
  },
  {
    pkg: '@types/react',
    file: 'global.d.ts',
    virtualPath: 'file:///node_modules/@types/react/global.d.ts',
  },
  {
    pkg: 'csstype',
    file: 'index.d.ts',
    virtualPath: 'file:///node_modules/csstype/index.d.ts',
  },
  {
    pkg: '@types/prop-types',
    file: 'index.d.ts',
    virtualPath: 'file:///node_modules/@types/prop-types/index.d.ts',
  },
];

const versions = new Map<string, string>();
const entries = LIBS.map(({ pkg, file, virtualPath }) => {
  const pkgDir = join(root, 'node_modules', pkg);
  const content = readFileSync(join(pkgDir, file), 'utf8');
  if (!versions.has(pkg)) {
    versions.set(pkg, JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8')).version);
  }
  return { virtualPath, content };
});

const versionComment = [...versions.entries()].map(([pkg, v]) => `${pkg}@${v}`).join(', ');

const output = `/**
 * AUTO-GENERATED by scripts/generate-editor-types.ts — do not edit by hand.
 * Sources: ${versionComment}
 *
 * Embedded .d.ts sources for the Monaco TypeScript worker (registered via
 * addExtraLib in lib/monaco/setup.ts). Regenerate after bumping the packages.
 */

export interface EditorExtraLib {
  virtualPath: string;
  content: string;
}

export const EDITOR_EXTRA_LIBS: EditorExtraLib[] = [
${entries
  .map(
    (e) => `  {
    virtualPath: ${JSON.stringify(e.virtualPath)},
    content: ${JSON.stringify(e.content)},
  },`
  )
  .join('\n')}
];
`;

const outPath = join(root, 'lib', 'monaco', 'react-types.generated.ts');
writeFileSync(outPath, output);
console.log(
  `Wrote ${outPath} (${(output.length / 1024).toFixed(0)} KB) from ${versionComment}`
);
